import esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const GZIP_BUDGET = 1536; // 1.5 KB

async function build() {
  const distDir = path.resolve(__dirname, 'dist');
  if (!fs.existsSync(distDir)) {
    fs.mkdirSync(distDir, { recursive: true });
  }

  await esbuild.build({
    entryPoints: [path.resolve(__dirname, 'src/t.ts')],
    bundle: true,
    minify: true,
    target: ['es2018'],
    format: 'iife',
    outfile: path.resolve(distDir, 't.js'),
    write: true,
  });

  const content = fs.readFileSync(path.resolve(distDir, 't.js'));
  const gzipped = zlib.gzipSync(content);

  console.log(`t.js size: ${content.length} bytes (raw), ${gzipped.length} bytes (gzip)`);
  if (gzipped.length > GZIP_BUDGET) {
    console.error(`FAIL: Gzip size (${gzipped.length} B) exceeds ${GZIP_BUDGET} B budget!`);
    process.exit(1);
  }
  console.log(`✓ Gzip size under budget (${gzipped.length} / ${GZIP_BUDGET} bytes)`);

  // Single source of truth:
  //  1. apps/web serves the exact built bundle (dev + Vercel static).
  //  2. apps/collect Worker imports it as a generated module.
  fs.copyFileSync(path.resolve(distDir, 't.js'), path.resolve(__dirname, '../../apps/web/public/t.js'));

  const bundleTs = `// AUTO-GENERATED by packages/tracker/build.mjs — do not edit.\nexport const TRACKER_JS = ${JSON.stringify(
    content.toString('utf8')
  )};\n`;
  fs.writeFileSync(path.resolve(__dirname, '../../apps/collect/src/tracker-bundle.ts'), bundleTs);

  console.log('✓ synced apps/web/public/t.js + apps/collect/src/tracker-bundle.ts');
}

build().catch((err) => {
  console.error(err);
  process.exit(1);
});
